version: '3.8'
services:
  loan-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loan-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: unless-stopped