server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:loan-dev
    driver-class-name: org.h2.Driver
    username: inghubs-dev
    password: inghubsdev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
logging:
  level:
    root: info