server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:loan-test
    driver-class-name: org.h2.Driver
    username: inghubs-test
    password: inghubstest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
logging:
  level:
    root: error