server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:loan-prod
    driver-class-name: org.h2.Driver
    username: inghubs-prod
    password: inghubsprod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    defer-datasource-initialization: true
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
logging:
  level:
    root: error